# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32aeb27755a02ded5b91864a2b346a8db6452f41ae976c8d40bf0290aceada64c530dc6cfcd959b118d8d91dcbc639dfcc017adb1f5031d6f65ca125792ec37b

test:
  secret_key_base: 8f7d0b6e6971983412c1c665fd0f6b722bffad44483980d61a8f281983cd1dff76c5438540eb361377dccf5e9a7aef68bfbaf19cea1172f904c1c377910719c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
